enabled_fonts:
  - 'local_fonts://work_sans'
  - 'local_fonts://work_sans_normal'
  - 'local_fonts://work_sans_semibold'
  - 'local_fonts://work_sans_medium'
load_all_enabled_fonts: 1
load_on_themes: {  }
_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
