simple_redirect.simple_redirect.*:
  type: config_entity
  label: 'Simple Redirect config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    from:
      type: string
      label: 'from'
    to:
      type: string
      label: 'from'
    uuid:
      type: string
